spring:
  application:
    name: supplier_service
  datasource:
    name: supplier_viet-bac_service
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI}
springdoc:
  api-docs:
    path: /supplier-service/v3/api-docs
  swagger-ui:
    path: /supplier-service/swagger/swagger-ui.html
    disable-swagger-default-url: true

external:
  product-service:
    url: ${PRODUCT_SERVICE_URL}
server:
  port: 8087