spring:
  application:
    name: warehouse_service
  datasource:
    name: warehouse_viet-bac_service
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  api-docs:
    path: /warehouse-service/v3/api-docs
  swagger-ui:
    path: /warehouse-service/swagger/swagger-ui.html
    disable-swagger-default-url: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${OAUTH2_ISSUER_URI}
#          jwk-set-uri: ${OAUTH2_JWK_SET_URI}

external:
  product-service:
    url: ${PRODUCT_SERVICE_URL}

server:
  port: 8082
