spring:
  application:
    name: employee_service
  datasource:
    name: employee_viet-bac_service
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  api-docs:
    path: /employee-service/v3/api-docs
  swagger-ui:
    path: /employee-service/swagger/swagger-ui.html
    disable-swagger-default-url: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${OAUTH2_ISSUER_URI}
#          jwk-set-uri: ${OAUTH2_JWK_SET_URI}
server:
  port: 8083
# Keycloak Configuration
keycloak:
  server-url: http://localhost:8180
  realm: optimization
  client-id: admin-cli
  username: admin
  password: admin

logging:
  level:
    root: INFO
    com.ecotel.employee_service: DEBUG
    org.hibernate.SQL: DEBUG
