services:
  transaction_mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3355:3306"
    volumes:
      - transaction_mysql_data:/var/lib/mysql

  doc_converter:
    build:
      context: .
      dockerfile: Dockerfile.libreoffice
    container_name: doc_converter
    volumes:
      - D:/ADMIN/Java Spring Boot/inventory-optimization/backend/transaction-service/tmp:/tmp
    tty: true

volumes:
  transaction_mysql_data: