FROM debian:12-slim

# Cài LibreOffice tối giản + font Arial (Liberation thay thế Arial)
RUN apt-get update && \
    apt-get install -y \
        libreoffice-core \
        libreoffice-writer \
        libreoffice-common \
        fonts-liberation \
        fonts-dejavu \
        ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Tạo user non-root
RUN useradd -ms /bin/bash libre

WORKDIR /app
USER libre

# Command giữ container sống
CMD ["bash"]