services:
  vehicle_mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3340:3306"
    volumes:
      - vehicle_mysql_data:/var/lib/mysql

volumes:
  vehicle_mysql_data: