services:
  plan_mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3341:3306"
    volumes:
      - plan_mysql_data:/var/lib/mysql

volumes:
  plan_mysql_data: