spring:
  application:
    name: transaction_service
  datasource:
    name: transaction_viet-bac_service
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
    ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
springdoc:
  api-docs:
    path: /transaction-service/v3/api-docs
  swagger-ui:
    path: /transaction-service/swagger/swagger-ui.html
    disable-swagger-default-url: true

external:
  product-service:
    url: ${PRODUCT_SERVICE_URL}
  warehouse-service:
    url: ${WAREHOUSE_SERVICE_URL}
  order-schedule-service:
    url: ${ORDER_SCHEDULE_SERVICE_URL}
  supplier-service:
    url: ${SUPPLIER_SERVICE_URL}

# File Upload/Download Configuration
app:
  template:
    path: template/
  output:
    path: output/
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${OAUTH2_ISSUER_URI}
#          jwk-set-uri: ${OAUTH2_JWK_SET_URI}
minio:
  url: http://localhost:8901
  access-key: admin
  secret-key: admin12345
  bucket: transactionfiles
server:
  port: 8085
