services:
  warehouse-site_mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3346:3306"
    volumes:
      - warehouse-site_mysql_data:/var/lib/mysql

volumes:
  warehouse-site_mysql_data: